--initialize needed data

INSERT INTO VOTE_ITEM (ID, NAME) VALUES (1,'電腦');;
INSERT INTO VOTE_ITEM (ID, NAME) VALUES (2,'滑鼠');;

INSERT INTO VOTE_RECORD (VOTER_NAME, ITEM_ID) VALUES ('Leo', 1);;
INSERT INTO VOTE_RECORD (VOTER_NAME, ITEM_ID) VALUES ('Sandy', 1);;
INSERT INTO VOTE_RECORD (VOTER_NAME, ITEM_ID) VALUES ('Sandy', 2);;
INSERT INTO VOTE_RECORD (VOTER_NAME, ITEM_ID) VALUES ('Randy', 2);;
INSERT INTO VOTE_RECORD (VOTER_NAME, ITEM_ID) VALUES ('RSY', 2);;